name: Build and Deploy to VM with Docker

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from .env
        uses: dotenv-linter/action-set-env@v1
        with:
          path: .env

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Build Docker image
        run: docker build -t hello-world-app .

      - name: Save Docker image as TAR
        run: docker save hello-world-app -o hello-world-app.tar

      - name: Deploy to VM with Docker
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ env.VM_HOST }}
          username: ${{ env.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            docker rm -f hello-world-app || true
            docker load -i hello-world-app.tar
            docker run -d -p 8080:8080 --name hello-world-app hello-world-app
