name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'   
          java-version: '17'        
          java-package: 'jdk'       
          architecture: 'x64'       
          check-latest: false       
          server-id: github         
          server-username: ${{ github.actor }}   
          server-password: ${{ secrets.GITHUB_TOKEN }} 
          overwrite-settings: true                

      - name: Build with Maven
        run: mvn clean install
